spring:
  application:
    name: breakground
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
      url: jdbc:postgresql://localhost:5432/breakground
      username: breakground
      password: breakground

chat:
  reportable-duration: 15m
  deletion-delay: 10m
  cleanup-interval-ms: 60000
report:
  evidence-retention: 30d
  cleanup-interval-ms: 60000
